/* libltdlS.c - symbol resolution table for `libltdl' dlsym emulation. */
/* Generated by libtool (GNU libtool) 2.4.2 */

#ifdef __cplusplus
extern "C" {
#endif

#if defined(__GNUC__) && (((__GNUC__ == 4) && (__GNUC_MINOR__ >= 4)) || (__GNUC__ > 4))
#pragma GCC diagnostic ignored "-Wstrict-prototypes"
#endif

/* Keep this code in sync between libtool.m4, ltmain, lt_system.h, and tests.  */
#if defined(_WIN32) || defined(__CYGWIN__) || defined(_WIN32_WCE)
/* DATA imports from DLLs on WIN32 con't be const, because runtime
   relocations are performed -- see ld's documentation on pseudo-relocs.  */
# define LT_DLSYM_CONST
#elif defined(__osf__)
/* This system does not cope well with relocations in const data.  */
# define LT_DLSYM_CONST
#else
# define LT_DLSYM_CONST const
#endif

/* External symbol declarations for the compiler. */
extern int dlopen_LTX_get_vtable();

/* The mapping between symbol names and symbols.  */
typedef struct {
  const char *name;
  void *address;
} lt_dlsymlist;
extern LT_DLSYM_CONST lt_dlsymlist
lt_libltdl_LTX_preloaded_symbols[];
LT_DLSYM_CONST lt_dlsymlist
lt_libltdl_LTX_preloaded_symbols[] =
{  { "libltdl", (void *) 0 },
  {"dlopen.a", (void *) 0},
  {"dlopen_LTX_get_vtable", (void *) &dlopen_LTX_get_vtable},
  {0, (void *) 0}
};

/* This works around a problem in FreeBSD linker */
#ifdef FREEBSD_WORKAROUND
static const void *lt_preloaded_setup() {
  return lt_libltdl_LTX_preloaded_symbols;
}
#endif

#ifdef __cplusplus
}
#endif
